version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3001:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - app-network
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    user: 'root'
    volumes:
      - ./monitoring/loki/local-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki:/tmp/loki
    networks:
      - app-network
volumes:
  grafana_data:

networks:
  app-network:
    driver: bridge
